### ISSUE TITLE
[bug]: Desktop version does not respect order of parameters in multipart/form-data requests

### ISSUE THREAD

**Issue by blakepierce** [hoppscotch/hoppscotch#3791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This issue appears to be the same as [this issue](https://github.com/hoppscotch/hoppscotch/issues/1833) which has been resolved but it now exists in the desktop version. (I am on an Apple M1 Pro Mac running OS 14.3 and Hoppscotch 23.12.1-1 (20231224.122102))

When sending a POST request using the multipart/form-data content type, it is expected that the fields in the body are sent in the same order they appear in the UI. In reality, the fields are re-ordered (it appears alphabetically). This causes issues for APIs which expect parameters to be sent in a particular order. 

For example, if I have an API that expects two parameters, 'name' (a string) and 'file' (a file),  and it requires 'name' to be provided first, it is impossible to send a proper request using Hoppscotch. Even if 'name' is listed above 'file' in the UI, the parameters will be re-ordered alphabetically when the request is sent and 'file' will be listed first.

### Steps to reproduce

1. Set up a test API such that you can see the order of parameters sent in the request body
2. In Hoppscotch, click on REST
3. Create a POST request with a body of content type multipart/form-data
4. Provide 2 or more parameters in the request body
5. Drag the parameters to order them. Ensure they are in a non-alphabetical order
6. Send the request
7. In your test API, notice the order of the parameters. They have been re-ordered alphabetically

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. We’ve fixed this bug in the latest release.
[Download the latest builds](https://hoppscotch.com/download) and provide your valuable feedback.

Closing this ticket as this bug is now fixed in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by emanuel-achirei-deel** [comment]
I just downloaded the latest build and the issue is still happening.

**Comment by emanuel-achirei-deel** [comment]
@liyasthomas thanks for reopening, I've reported the bug with repro steps here as well: https://github.com/hoppscotch/hoppscotch/issues/4889

**Comment by CuriousCorrelation** [comment]
Hi, the latest agent [v0.1.7](https://github.com/hoppscotch/agent-releases/releases/tag/v0.1.7) and the desktop app [v25.2.3](https://github.com/hoppscotch/releases/releases/tag/v25.2.3-0) release should fix this issue.

Since this is already being tracked at https://github.com/hoppscotch/hoppscotch/issues/4889, closing this in favor of the new one targeted towards the new desktop app. Please follow up there if you continue experiencing problems after updating.
