### ISSUE TITLE
[bug]: Cannot login using Magic Link in windows 11 desktop application

### ISSUE THREAD

**Issue by nourkilany** [hoppscotch/hoppscotch#3803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I choose to login with email and type my company email and click on magic link it says that the magic link is sent to my email although I don't get any emails.

Upon inspecting I found that there is a request that return 403 to the url `https://identitytoolkit.googleapis.com/v1/accounts`
and the response body is 

```
{
  "error": {
    "code": 403,
    "message": "Requests from referer https://tauri.localhost are blocked.",
    "errors": [
      {
        "message": "Requests from referer https://tauri.localhost are blocked.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/421993993223",
          "service": "identitytoolkit.googleapis.com"
        }
      }
    ]
  }
}

```

When I login from the web client it sends the emails just fine this is exclusive to the desktop application
PS: I have the latest hoppscotch version installed and I am on Windows 11

### Steps to reproduce

1. Go to login
2. Click on continue with email
3. write email
4. nothing arrives to the inbox

### Environment

Production

### Version

Cloud

**Comment by sibbl** [comment]
Same issue here. Email magic link login via browser works fine. Email magic link login via Windows app is broken.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. We’ve fixed this bug in the latest release.
[Download the latest builds](https://hoppscotch.com/download) and provide your valuable feedback.

Closing this ticket as this bug is now fixed in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by transtone** [comment]
> Thanks for your patience and valuable feedback. We’ve fixed this bug in the latest release. [Download the latest builds](https://hoppscotch.com/download) and provide your valuable feedback.
> 
> Closing this ticket as this bug is now fixed in the recent version. Please feel free to reach out if you have any other concerns.

not fixed yet.

 `There was an error processing your login...`  when process login in web browser.

`v2025.4.2`
