### ISSUE TITLE
[bug]: Code generation not working

### ISSUE THREAD

**Issue by gduverger** [hoppscotch/hoppscotch#4052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I click "Show code," a popup appears with an error message saying, "Something went wrong." This happens with every language I select. I was expecting to see code generated in the selected language to replicate the query. Specifically, I want to view the cURL generated code to help debug another issue I'm facing.

### Steps to reproduce

1. Create a new request
2. Click the Options dropdown (next to Send)
3. Click Show code
4. See the “Something went wrong” error

<img width="518" alt="Screenshot 2024-05-09 at 10 12 13 AM" src="https://github.com/hoppscotch/hoppscotch/assets/93743/c9f6e02e-f358-4ca8-9dae-4ee96ca0cb7c">

### Environment

Production

### Version

Local

**Comment by JoelJacobStephen** [comment]
@gduverger Thanks for reporting this issue.

We've identified the cause of this issue and opened a PR (https://github.com/hoppscotch/hoppscotch/pull/4033) to fix this. This will be patched in the next immediate point release.

Possibly a duplicate of https://github.com/hoppscotch/hoppscotch/issues/4008 , https://github.com/hoppscotch/hoppscotch/issues/4036.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by stephenc-dg** [comment]
I'm still getting this same error on version 2025.4.1

![Image](https://github.com/user-attachments/assets/f0937e58-49ca-43d3-aa2a-0a157484e38c)
