### ISSUE TITLE
[bug]: json Socket.io messages are sent as string instead of object

### ISSUE THREAD

**Issue by Tlepel** [hoppscotch/hoppscotch#4570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I have connected to any (Socket.io) server and try to send an object, the message sent includes a serialized message containing the serialized object.

For example: `420["test-message","{\n  \"key\": \"value\"\n}"]`

### Steps to reproduce

1. Connect to wss://echo-socketio.hoppscotch.io with Client v4
2. Send a message `'test-message'` with the following body:
   ```
   {
     "key": "value"
   }
   ```
Observe through the network tab of your browser that the message sent is `420["test-message","{\n \"key\": \"value\"\n}"]`.

When the same message is sent directly through a socket.io client, (using `emit('test-message', {key: "value"});`) the message sent is `42["test-message",{"key":"value"}]`
Note the omission of all white-space characters, since the socket.io default parser is used instead.

### Environment

Production

### Version

Cloud

**Comment by Tlepel** [comment]
This can probably be solved by performing a few more steps in this method:
https://github.com/hoppscotch/hoppscotch/blob/908f936f50b6b22ea556e7cd92ea14fae3721672/packages/hoppscotch-common/src/components/realtime/Communication.vue#L238-L246

If this is adapted to use `JSON.parse(comminucationBody.value)` if `contentType` is 'JSON', that would probably solve the issue entirely.

**Comment by dollannn** [comment]
Also having this issue

**Comment by KennethB09** [comment]
This issue is still not fixed.
I'm encountering a problem when sending a JSON message in Socket.IO mode.

In the Network tab, I can see that the payload is sent as:

`420["eventName","{\n  \"key\": \"value\"\n}"]
`
Expected behavior:

42["eventName",{"key":"value"}]

This requires manual JSON.parse() on the server side, which should not be necessary when emitting JSON in Socket.IO mode.
