### ISSUE TITLE
[bug]: GraphQL Connect Not Sending Headers or Bearer Token

### ISSUE THREAD

**Issue by AlexGall24** [hoppscotch/hoppscotch#4727]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

There is currently an issue with the GraphQL connect feature. When making a request, the headers and the bearer token specified in the options are not being sent. This results in authentication failures when connecting to secured GraphQL endpoints.

![Image](https://github.com/user-attachments/assets/0942ba19-0177-42ca-bfea-38a2b4711ecf)

### Steps to reproduce

1.-Open Hoppscotch and switch to the GraphQL tab.
2.-Enter a valid GraphQL endpoint URL.
3.-Add necessary headers, including an Authorization header with a bearer token.
4.-Send the request. (click connect).
5.-Inspect the request headers and observe that the specified headers and bearer token are missing in the backend.
6.-Hoppscotch shows error: 'Failed to fetch graphql schema due to network error'.

### Environment

Production

### Version

Cloud

**Comment by jamesgeorge007** [comment]
Hi, this is fixed in the [v2025.2.0 release](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.2.0). Please feel free to let us know if you have any feedback.

**Comment by ohmyhusky** [comment]
It doesn't work on 2025.2.3 (I only tested the Docker image), but when I tried it with 2025.2.0 it does work

**Comment by jasondamour** [comment]
I'm still seeing this issue in `Version 25.3.2 (20250415.085230)` (Macos Native app AND web demo)

**Comment by jamesgeorge007** [comment]
Hi @ohmyhusky @jasondamour, could you check if this issue is reproducible in the latest release? If it does, appreciate more context or detailed steps to reproduce it. Thanks!

**Comment by filipjnc** [comment]
Doesn't work. Can't connect to Tableau.
