### ISSUE TITLE
[feature]: Remember last active server instance in desktop app

### ISSUE THREAD

**Issue by LordSimal** [hoppscotch/hoppscotch#4828]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

The desktop app should remember what server instance was active last time the app was open.

### Why should this be worked on?

In the latest hoppscotch release it is possible to connect the desktop app to a self hosted instance 🥳 

What I noticed is the fact, that after closing and re-opening the app it doesn't remember, that I had my self-hosted instance active. It defaults to the on-prem version, which I have not connected (no offence, it surely works great, but I prefer my data to be self-hosted if possible 😁)

It would be nice if the app could remember, what my latest active server instance was instead of me having to re-open my self-hosted instance again after closing and re-opening the app.

Another option would be to mark a specific instance as "favorite" - and that one will get opened by default when starting the app.

**Comment by brunnobb** [comment]
Same happens to me..

I closed desktop version while connected to my on premises instance.

When I reopen, my instance name is shown on the left side. But the login info and the Workspace data belong to the hoppscotch.io instance

![Image](https://github.com/user-attachments/assets/76ebe32c-30ca-4542-be05-f0933e7c64d0)

To fix it, i have to select hoppscotch cloud app on the left side, and move back to my personal instance, then everything works as expected.

**Comment by muellerst-hg** [comment]
also happens on my system:
self-hosted community server, 2025.2.2
desktop app 2025.2.2

**Comment by John-jk** [comment]
Why the feature label? It's a bug.

I have the same as others. When opening a desktop app, my server is selected, but the request (for example) for authorization is created for the hoppscotch.io server.

![Image](https://github.com/user-attachments/assets/09a03210-0158-43fe-9710-942c086c5b17)

![Image](https://github.com/user-attachments/assets/09d9a716-3936-4edc-8262-429f38f52612)

As already written above. Switching to the cloud version and back helps, BUT you have to do this every time you launch the desktop app.

**Comment by Pezhvak** [comment]
I'm here to report the same issue.

**Comment by lamongabriel** [comment]
This is also happening with my team, would be great to have an option to select a default instance + delete the SaaS one.
In teams using a self-hosted version of the app, we don't use the SaaS at all, would be nice to remove it to avoid confusion.

Thank you

**Comment by liyasthomas** [comment]
> This is also happening with my team, would be great to have an option to select a default instance + delete the SaaS one. In teams using a self-hosted version of the app, we don't use the SaaS at all, would be nice to remove it to avoid confusion.
> 
> Thank you

@lamongabriel, you can download self-hosted desktop apps from the [releases page](https://github.com/hoppscotch/releases/releases). While we’re improving the platform to provide better support for only self-hosted instances, please be patient.

**Comment by riteshbxr** [comment]
I would like some option to change default or reload the last loaded instance

**Comment by nenatalya** [comment]
I'm here to report this issue too

**Comment by FedorQApro** [comment]
PLS, do it

**Comment by ilya1731** [comment]
Please fix it as soon as possible

**Comment by emil-johansson-99** [comment]
We are also waiting for this issue to be resolved before rolling out the desktop app in our organization. With all respect I understand that the maintainers of Hoppscotch have alot to do, maybe it can be assigned to someone else?

**Comment by aintuit** [comment]
+1

**Comment by faritor** [comment]
it would be even better if the instance name could be modified

**Comment by mashmex** [comment]
Our org also needs this feature to get a flawless client application login at every start of the work day. At the moment, it still opens the cloud environment which we are not using, as we use on-prem server.

**Comment by DanielProtopopov** [comment]
Here to report the same issue

**Comment by SuperRoach** [comment]
This is still a problem? Noticed the same when I tried it as well.

**Comment by Pezhvak** [comment]
I don't think they ever fixed this.

> This is still a problem? Noticed the same when I tried it as well.

**Comment by jamesgeorge007** [comment]
Hi, this is addressed in #5421, scheduled for the upcoming major release.

**Comment by lamongabriel** [comment]
Thank you!

**Comment by jamesgeorge007** [comment]
Closing since this is now addressed in the [v2025.11.0 release](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.11.0). Please let us know if you have any feedback.

**Comment by enricojonas** [comment]
Was this supposed to fix the switching between instances? For me it's still not working with Desktop Client 2025.11.2. After adding a self hosted instance, it's showing it as selected on each startup, but it seems it's not in the correct context. I need to switch to "HOPPSCOTCH DESKTOP", and then switch back again to my self-hosted instance to make it work. Seems it's the same behavior like before?!

**Comment by wmbin** [comment]
25.12.1 The same problem

**Comment by mudora23** [comment]
2025.12.1 same problem on Mac Desktop App
