### ISSUE TITLE
[bug]: Environment variables / values missing after update

### ISSUE THREAD

**Issue by AryaSvitkona** [hoppscotch/hoppscotch#5104]
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Current behavior

With the latest Update to 25.5 all environment variable keys are persistent, but the values are gone.

![Image](https://github.com/user-attachments/assets/64de1517-c183-46df-808d-815f0554ef70)

I also receive a "schema validation error" while loading the App or the Chrome App on OSX.

![Image](https://github.com/user-attachments/assets/11986d3b-ae9f-41ef-a365-75f55b580de4)

### Steps to reproduce

1) Start Hoppscotch (PWA or native app)
2) Update to latest 25.5 version
3) Check environment variables / values

### Logs and Screenshots

```shell

```

### Environment

Production

### Hoppscotch Version

Cloud

### Interceptor

Not Applicable - Issue not related to network requests

### Operating System

MacOS

**Comment by furai** [comment]
#5055 - This is actually what caused the bug for me. It didn't migrate properly the values I had in my environment. It moved them to initialValue without filling in the current value. And apparently only current value is used in requests.

**Comment by mpereira-lab** [comment]
I'm adding to this issue that in both exports and imports, the `currentValue` is not being taken into account.

**Comment by jdndm** [comment]
Confirming this is broken using the webapp with synced environments via shared workspace

**Comment by scottym5797** [comment]
> Hi, this has been addressed in the latest release. Please let us know if the issue persists. The code generation issue mentioned above should also be resolved. For any other concerns related to scripting or similar areas, feel free to open a new issue with steps to reproduce.

I'm still facing this issue. I set up the shared environment, so it seems to work for me even when throwing the Schema erroa. But someone else accessing the shared ENV has issues and can't access the variables.

<img width="728" alt="Image" src="https://github.com/user-attachments/assets/28c1a185-987e-449f-b779-934afe39db7d" />

**Comment by rintaaaa** [comment]
![Image](https://github.com/user-attachments/assets/cb15e6bc-5dd0-4f1b-a38b-95fa63d7683b)
I also updated to v25.5.1, but I'm experiencing the same situation. Additionally, I can no longer import.

**Comment by AbhishekPrajapati** [comment]
We are getting the same issue all of sudden, leaving all our saved requests changed to Untitled - I think they are lost now. When reloading the page, getting below errors:

![Image](https://github.com/user-attachments/assets/3d5854be-d7c1-4eba-a212-7fc5330eaab2)

We got some exported collection(exported from Hoppscotch only, which has saved responses too) but when importing it, they are still showing `Untitled` requests, any thoughts on this?

**Comment by swotiendang** [comment]
Most of issues in this thread happened to my team, we start using Hoppscotch from March 2025, and 3 months later lots of AI failed, waiting for  the fix from team.

**Comment by nivedin** [comment]
> We are getting the same issue all of sudden, leaving all our saved requests changed to Untitled - I think they are lost now. When reloading the page, getting below errors:
> 
> ![Image](https://github.com/user-attachments/assets/3d5854be-d7c1-4eba-a212-7fc5330eaab2)
> 
> We got some exported collection(exported from Hoppscotch only, which has saved responses too) but when importing it, they are still showing `Untitled` requests, any thoughts on this?

@AbhishekPrajapati can you please share your'e exported collection, this can help us with debugging the issue.

**Comment by AbhishekPrajapati** [comment]
> > We are getting the same issue all of sudden, leaving all our saved requests changed to Untitled - I think they are lost now. When reloading the page, getting below errors:
> > ![Image](https://github.com/user-attachments/assets/3d5854be-d7c1-4eba-a212-7fc5330eaab2)
> > We got some exported collection(exported from Hoppscotch only, which has saved responses too) but when importing it, they are still showing `Untitled` requests, any thoughts on this?
> 
> [@AbhishekPrajapati](https://github.com/AbhishekPrajapati) can you please share your'e exported collection, this can help us with debugging the issue.

Sorry @nivedin I cannot share my collection due to my company's security policies.

**Comment by agu3rra** [comment]
@AbhishekPrajapati if you have your collection previously saved in Hoppscotch's JSON form, not all is lost. I had a peer simply download an older version of Hoppscotch and it opened fine (all the `Untitled` requests/responses were there).

**Comment by imrinzzzz** [comment]
I have a similar issue, but I don't have a backup. Does that mean I cannot get the values back?

**Comment by agu3rra** [comment]
> I have a similar issue, but I don't have a backup. Does that mean I cannot get the values back?

I don't know, but I suggest you simply try to leave it as it is and install the older version without removing the current one. Alternatively, try to export the current messed up ENV before you do that. Perhaps I shows all requests as "Untitled", but the JSON has the actual data in there?

**Comment by imrinzzzz** [comment]
> > I have a similar issue, but I don't have a backup. Does that mean I cannot get the values back?
> 
> I don't know, but I suggest you simply try to leave it as it is and install the older version without removing the current one. Alternatively, try to export the current messed up ENV before you do that. Perhaps I shows all requests as "Untitled", but the JSON has the actual data in there?

Heyyy, so I just installed an older version and almost everything was still there. The only things that couldn't be restored were the changes made in the new version of the app.

**Comment by tanardi94** [comment]
Is there any progress for this bugfix?
I kinda move to postman til this bug is fixed, Love this app bro

**Comment by keliansb** [comment]
We still have this issue after upgrading to [v2025.5.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.5.2)

**Comment by nivedin** [comment]
> We still have this issue after upgrading to [v2025.5.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.5.2)

@keliansb are you facing this issue with personal or a shared workspace environment

**Comment by keliansb** [comment]
@nivedin with shared workspace environment
I don't know if personal workspace is impacted by this issue because we don't use it

**Comment by nivedin** [comment]
> [@nivedin](https://github.com/nivedin) with shared workspace environment I don't know if personal workspace is impacted by this issue because we don't use it

@keliansb was there any error popup you saw with persistance error ?

**Comment by keliansb** [comment]
@nivedin yes, indeed:

![Image](https://github.com/user-attachments/assets/2a0eb9e5-21ab-4efb-a0eb-5b47164d8e20)

**Comment by nivedin** [comment]
> [@nivedin](https://github.com/nivedin) yes, indeed:
> 
> ![Image](https://github.com/user-attachments/assets/2a0eb9e5-21ab-4efb-a0eb-5b47164d8e20)

@keliansb can you try clearing cache and try again.

**Comment by keliansb** [comment]
@nivedin just tried in a private window. No popup but environment variables are still empty.

**Comment by nivedin** [comment]
> [@nivedin](https://github.com/nivedin) just tried in a private window. No popup but environment variables are still empty.

@keliansb thank you for the information, need some more info for debugging this issue.

Can you please send me the value from the network tab of `GetTeamEnvironments`

![Image](https://github.com/user-attachments/assets/2328697e-c739-4c15-af7e-2fd9c9e54cea)

**Comment by keliansb** [comment]
@nivedin sure, here it is:
```
{
  "operationName": "GetTeamEnvironments",
  "query": "query GetTeamEnvironments($teamID: ID!) {\n  team(teamID: $teamID) {\n    teamEnvironments {\n      id\n      name\n      variables\n      teamID\n    }\n  }\n}",
  "variables": {
    "teamID": "cm3x7ajvf000mcyuq41jrxvmy"
  }
}
```

**Comment by nivedin** [comment]
> [@nivedin](https://github.com/nivedin) sure, here it is:
> 
> ```
> {
>   "operationName": "GetTeamEnvironments",
>   "query": "query GetTeamEnvironments($teamID: ID!) {\n  team(teamID: $teamID) {\n    teamEnvironments {\n      id\n      name\n      variables\n      teamID\n    }\n  }\n}",
>   "variables": {
>     "teamID": "cm3x7ajvf000mcyuq41jrxvmy"
>   }
> }
> ```

@keliansb Thank you for the info, just one more thing. Can you send the response object of this network call, like this. You can hide the values if any secrets exists.

https://github.com/user-attachments/assets/3da66005-b755-4f0c-8339-284e0bab30cd

**Comment by keliansb** [comment]
@nivedin it looks like the values from `Prod` and `Test` environments are still there, but nothing for `Staging`.
Also please note that I can see the values for the environment `Test` in Hoppscotch, but not for `Prod`.
```
{
	"data": {
		"team": {
			"teamEnvironments": [
				{
					"id": "cm3yk2ufl0001ov3dwmtk93q0",
					"name": "Prod",
					"variables": "[{\"key\":\"netbox_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"rocketchat_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"realtime_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"realtime_domainName\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"realtime_apikey\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"realtime_customer\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"realtime_contact\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"wikijs_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"gitlab_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"gitlab_api_version\",\"value\":\"v4\",\"secret\":false},{\"key\":\"gitlab_access_token\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"gitlab_project_id\",\"value\":\"530\",\"secret\":false},{\"key\":\"test\",\"value\":\"opened\",\"secret\":false},{\"key\":\"gitlab_merge_request_iid\",\"value\":\"10\",\"secret\":false},{\"key\":\"realtime_registrant\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"keycloak_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"keycloak_realm\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"pdns_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"pdns_apikey\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"pdns_domainname\",\"secret\":true},{\"key\":\"glpi_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"wikijs_host\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"wikijs_apikey_key\",\"secret\":true},{\"key\":\"wikijs_apikey_value\",\"secret\":true},{\"key\":\"ROCKET_CHAT_TOKEN\",\"secret\":true},{\"key\":\"ROCKET_CHAT_USERID\",\"secret\":true}]",
					"teamID": "cm3x7ajvf000mcyuq41jrxvmy"
				},
				{
					"id": "cm473snwg000jaczqlrt9xt0v",
					"name": "Test",
					"variables": "[{\"key\":\"groupid\",\"value\":\"<omitted>\",\"secret\":false},{\"key\":\"channelid\",\"value\":\"<omitted>\",\"secret\":false}]",
					"teamID": "cm3x7ajvf000mcyuq41jrxvmy"
				},
				{
					"id": "cm3yk2xps0003ov3dqnfp2iap",
					"name": "Staging",
					"variables": "[{\"key\":\"netbox_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"rocketchat_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"rocketchat_username\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"authToken\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"userId\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"netbox_token\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"rocketchat_password\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_domainName\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_customer\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_contact\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_apikey\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"paypal_access_token\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"realtime_registrant\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"keycloak_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"keycloak_realm\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"glpi_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"glpi_app_token\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"glpi_userapi_token\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"glpi_session_token\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"pdns_host\",\"secret\":false,\"currentValue\":\"\"},{\"key\":\"pdns_apikey\",\"secret\":false,\"currentValue\":\"\"}]",
					"teamID": "cm3x7ajvf000mcyuq41jrxvmy"
				}
			]
		}
	}
}
```

**Comment by chanhh01** [comment]
are there any existing pre-request script that can help to paste whatever written in initial value to current value?
developers without editor role didnt have locally saved current value in environment in the first place, and somehow the environment variables didnt even try to get initial value when current value is empty..

**Comment by nivedin** [comment]
> are there any existing pre-request script that can help to paste whatever written in initial value to current value? developers without editor role didnt have locally saved current value in environment in the first place, and somehow the environment variables didnt even try to get initial value when current value is empty..

@chanhh01 we have a [fix](https://github.com/hoppscotch/hoppscotch/pull/5162) for this issue in the coming patch release.

**Comment by AryaSvitkona** [comment]
I register three pull request, a new version but the issue is still open.

May I kindly ask what the expected status should be with latest version 25.5.2, from the perspective of a Hubspot product owner?
- Can users migrate from 25.4.x to 25.5.2 without lose environment variables?
- Users with version 25.5.x with the mentioned bug, can migrate to 25.5.2 without lose environment variables?
- Should users copy paste each initial value by hand to current value for having a working environment?

As creator of the Issue I also still can't access to my environment variable values although using latest version.
@nivedin I just checked the mentioned (a few comments above) response object for our team and there I can still see the values we should see in the app.

**Comment by nivedin** [comment]
> I register three pull request, a new version but the issue is still open.
> 
> May I kindly ask what the expected status should be with latest version 25.5.2, from the perspective of a Hubspot product owner?
> 
> * Can users migrate from 25.4.x to 25.5.2 without lose environment variables?
> * Users with version 25.5.x with the mentioned bug, can migrate to 25.5.2 without lose environment variables?
> * Should users copy paste each initial value by hand to current value for having a working environment?
> 
> As creator of the Issue I also still can't access to my environment variable values although using latest version. [@nivedin](https://github.com/nivedin) I just checked the mentioned (a few comments above) response object for our team and there I can still see the values we should see in the app.

@AryaSvitkona sorry for the delayed response, yes you can upgrade to the latest version 25.5.3 without the lose of environment value. 
We have fixed all the existing bug's like response getting lost and team environment values missing. Most of the issue was with version migration.
Also we have made a small change in the environment execution flow where the initial value is picked up in request execution time if the current value is empty.
We did an internal testing and everything is working fine from our end. Please try it from your end an let me know.

**Comment by AryaSvitkona** [comment]
Thank you for your effort!
I can confirm, that after update to 25.5.3, the environment variables are back and requests are working like before.
Also the values from initial_value are copied to current_value.
![Image](https://github.com/user-attachments/assets/bf78bd50-278e-4595-9ba6-ee786a32ddcb)

**Comment by chanhh01** [comment]
![Image](https://github.com/user-attachments/assets/59f27cc0-0678-4667-b0ae-64820df95fd4)

what about initial value as default when current value is empty?
I had ady reloaded hoppscotch after the new version found prompt.

and i also found out that project environment variable (idk if they count as global environment variable), initial variable is still not copied to current value (tried this on both editor and viewer role) as per mentioned by AryaSvitkona for me

**Comment by liyasthomas** [comment]
The initial value won’t be automatically copied to the current value. Instead, when the current value is empty, it will fall back to its initial value. The tooltip displays the current value. If it’s empty, it shows an empty placeholder but falls back to the initial value. Once the current value is populated, the tooltip displays the actual or modified value. We’ll strive to display both the initial and current values in the tooltip.

This ticket can be closed as a fix, as it’s already available in the recent release.

**Comment by abhagsain** [comment]
This is still happening, and it's so annoying

**Comment by chanhh01** [comment]
> This is still happening, and it's so annoying

Same
I actually given up the initial value approach and just let all my colleagues have write access so that they can copy the value from initial value to current value themselves.
