### ISSUE TITLE
[feature]: Collection variables cannot reference other collection variables within the same collection

### ISSUE THREAD

**Issue by AaronFortG** [hoppscotch/hoppscotch#5583]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Right now, if you create collection variables in Hoppscotch, you can't use one variable inside another variable in the same collection. For example, if I have a variable called URL set to "https://api.example.com/" and I want to create another variable called API_URL that uses <<URL>>/v1, it doesn't work - it just stays as the literal text "<<URL>>/v1" instead of becoming "https://api.example.com/v1". This is frustrating because environment variables can do this just fine, but collection variables can't, even though they should work the same way.

<img width="767" height="312" alt="Image" src="https://github.com/user-attachments/assets/7e1f867a-9059-444c-99d1-4c27659860a3" />

### Why should this be worked on?

This is a really common problem that makes organizing API collections much harder than it should be. When I'm testing APIs, I often want to build up my URLs step by step - like having a base URL, then an API version URL that uses the base URL, then specific endpoint URLs that use the API version URL. Right now, I have to either copy and paste the same URL parts over and over again (which is error-prone and annoying to maintain) or I have to give up on using collection variables and use environment variables instead (but then I lose the benefit of having variables that belong to specific collections only and it's get a bit messy). This feels like a basic feature that should just work, especially since the code to make it work already exists in Hoppscotch - it's just not being used for collection variables. It would make managing complex API collections so much easier and less repetitive.

**Comment by AaronFortG** [comment]
Seems that the Collection variable works in the Request but it's not being resolved on the "Collection Properties" nor on the "Code Snippet" code generation.

<img width="1844" height="682" alt="Image" src="https://github.com/user-attachments/assets/5628d9bf-c5c6-44dd-b1ff-54a6d0c469ab" />

As for the code generation, I have been digging around the code and this seems to be related to only passing the environment when generating the snippet code:

<img width="869" height="682" alt="Image" src="https://github.com/user-attachments/assets/b173f9a9-7f89-4ba9-babf-b4129b7198d8" />

I believe the getEffectiveRESTRequest should also have the collection variables and also the globals (they do not appear either).

<img width="958" height="898" alt="Image" src="https://github.com/user-attachments/assets/453cc675-4a25-4fa1-82ae-bac024d24264" />

**Comment by nivedin** [comment]
@AaronFortG Thank you for reporting the bugs and providing a detailed summary. I’ve pushed a [PR](https://github.com/hoppscotch/hoppscotch/pull/5584) to fix this issues, it will likely be live in the next release.

**Comment by AaronFortG** [comment]
> [@AaronFortG](https://github.com/AaronFortG) Thank you for reporting the bugs and providing a detailed summary. I’ve pushed a [PR](https://github.com/hoppscotch/hoppscotch/pull/5584) to fix this issues, it will likely be live in the next release.

That's awesome, thanks for the quick response ^^

I tried looking it by myself but I am new on the project and I don't have any background nor context about the project, so I was not able to deal with it :(

**Comment by jamesgeorge007** [comment]
Hi, the above fix is now merged and scheduled for the upcoming major release.

**Comment by AaronFortG** [comment]
> Hi, the above fix is now merged and scheduled for the upcoming major release.

Awesome, thanks for the great work ☺️

**Comment by jamesgeorge007** [comment]
Closing since this is now addressed in the [v2025.11.0 release](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.11.0).

**Comment by AaronFortG** [comment]
Hey @jamesgeorge007 @nivedin, seem I am still experiencing some issues regarding the variable resolution. I am trying to migrate an entire project from Postman to Hoppscotch. I have exported the Globals, Environments and Collections as Json from Postman and imported them into Hoppscotch.

**These are my Global variables:**

<img width="748" height="318" alt="Image" src="https://github.com/user-attachments/assets/4d983bd9-6a31-4210-919f-f3f59577a111" />

**These are my Environment variables:**

<img width="741" height="290" alt="Image" src="https://github.com/user-attachments/assets/b83e929e-330e-4e4b-852e-8017a926be4b" />

**These are my Collection variables:**

<img width="767" height="222" alt="Image" src="https://github.com/user-attachments/assets/a5647c20-338b-4285-9a74-c7c4384f743f" />

All initial values are the same as current ones, so everything is up to date.

In the request URL seems the variable is resolved correctly. However, when making the request, it seems the conversion from the Enviroment + Colelction variables when making the request is not done correctly as shown in the "Code Snippet Generation" and the request's body returned.

This is the code generated from the request to `<<BASE_URL>>`, formed by `<<API_BASE_URL>><<API_PORT>>`:

```sh
curl --request GET \
  --url https:///%7B%7BHTTP%7D%7D%7B%7BAPI_BASE%7D%7D:1234
```

<img width="1756" height="1191" alt="Image" src="https://github.com/user-attachments/assets/f8d8d380-5d4e-4670-a1cd-fd9aefa99049" />

**Comment by nivedin** [comment]
I'm sorry for the delayed response @AaronFortG 

Can you check see if changing the Environment variables {{BASE}} and {{HTTP}}{{API_BASE}} to << BASE >> and << HTTP >><<API_BASE>> format fixes this issue.

**Comment by AaronFortG** [comment]
> I'm sorry for the delayed response [@AaronFortG](https://github.com/AaronFortG)
> 
> Can you check see if changing the Environment variables {{BASE}} and {{HTTP}}{{API_BASE}} to << BASE >> and << HTTP >><<API_BASE>> format fixes this issue.

Yeah, it's now working. I believe my main issue was related to importing from Postman, which was not converting correctly from `{{` to `<<` and `}}` to `>>` 😅. I created a PR which is already merged for next release that addresses this: #5704 

Using variables with ``<<` and `>>` inside Hoppscotch now is working correctly, thanks :)

**Comment by nivedin** [comment]
> > I'm sorry for the delayed response [@AaronFortG](https://github.com/AaronFortG)
> > Can you check see if changing the Environment variables {{BASE}} and {{HTTP}}{{API_BASE}} to << BASE >> and << HTTP >><<API_BASE>> format fixes this issue.
> 
> Yeah, it's now working. I believe my main issue was related to importing from Postman, which was not converting correctly from `{{` to `<<` and `}}` to `>>` 😅. I created a PR which is already merged for next release that addresses this: [#5704](https://github.com/hoppscotch/hoppscotch/pull/5704)
> 
> Using variables with ``<<`and`>>` inside Hoppscotch now is working correctly, thanks :)

Great to hear it’s working now and thank you for your contribution 🙌🏼
